manifest:
  projects:
    - name: golioth
      path: modules/lib/golioth
      revision: v0.5.0
      url: https://github.com/golioth/golioth-zephyr-sdk
      west-commands: scripts/west-commands.yml
      import:
        file: west-zephyr.yml
        path-prefix: deps
        name-allowlist:
          - zephyr
          - hal_espressif
          - hal_infineon
          - hal_nordic
          - hal_nxp
          - mbedtls
          - mcuboot
          - qcbor
  self:
    path: app
    west-commands: utility/west-commands/west-commands.yml
